import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { QRCodeSVG } from 'qrcode.react';
import axiosInstance from '../api/axiosInstance';

/**
 * AddStudentModal — slide-up modal for adding a new student.
 * On success shows the enrollment link + QR code.
 * Props:
 *   isOpen: boolean
 *   onClose: () => void
 *   onSuccess: () => void  (to refetch student list)
 */
const AddStudentModal = ({ isOpen, onClose, onSuccess }) => {
  const [form, setForm] = useState({ name: '', rollNumber: '', field: '', email: '' });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [enrollLink, setEnrollLink] = useState('');

  const handleChange = (e) => {
    setForm((prev) => ({ ...prev, [e.target.name]: e.target.value }));
    setError('');
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!form.name.trim() || !form.rollNumber.trim()) {
      setError('Name and Roll Number are required.');
      return;
    }
    setLoading(true);
    setError('');
    try {
      const { data } = await axiosInstance.post('/api/admin/students', form);
      setEnrollLink(data.enrollLink); // Uses the secure link generated by backend
      onSuccess?.();
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to add student. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    setForm({ name: '', rollNumber: '', field: '', email: '' });
    setError('');
    setEnrollLink('');
    onClose();
  };

  const copyLink = () => {
    navigator.clipboard.writeText(enrollLink);
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            className="fixed inset-0 z-40 bg-black/60 backdrop-blur-sm"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={handleClose}
          />

          {/* Modal */}
          <motion.div
            className="fixed inset-0 z-50 flex items-center justify-center p-4"
            initial={{ opacity: 0, scale: 0.94, y: 16 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.94, y: 16 }}
            transition={{ type: 'spring', stiffness: 300, damping: 28 }}
          >
            <div
              className="bg-slate-900 border border-slate-700/60 rounded-2xl w-full max-w-md shadow-2xl overflow-hidden"
              onClick={(e) => e.stopPropagation()}
            >
              {/* Header */}
              <div className="flex items-center justify-between px-6 py-4 border-b border-slate-700/50">
                <h2 className="text-lg font-semibold text-white">Add New Student</h2>
                <button
                  onClick={handleClose}
                  className="text-slate-400 hover:text-white transition-colors p-1 rounded-lg hover:bg-slate-700/50"
                  aria-label="Close modal"
                >
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>

              <div className="px-6 py-5">
                <AnimatePresence mode="wait">
                  {enrollLink ? (
                    /* Success state — show enrollment link */
                    <motion.div
                      key="success"
                      className="flex flex-col items-center gap-5 py-2"
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0 }}
                    >
                      <div className="w-12 h-12 rounded-full bg-emerald-500/15 border border-emerald-500/30 flex items-center justify-center">
                        <svg className="w-6 h-6 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                        </svg>
                      </div>
                      <div className="text-center">
                        <p className="text-white font-semibold">Student Added!</p>
                        <p className="text-slate-400 text-sm mt-1">Share this enrollment link with the student:</p>
                      </div>

                      {/* QR Code */}
                      <div className="bg-white p-3 rounded-xl">
                        <QRCodeSVG value={enrollLink} size={160} level="M" />
                      </div>

                      {/* Link + copy */}
                      <div className="w-full bg-slate-800 rounded-xl p-3 flex items-center gap-2">
                        <p className="text-xs text-slate-400 font-mono truncate flex-1">{enrollLink}</p>
                        <button
                          onClick={copyLink}
                          className="text-blue-400 hover:text-blue-300 text-xs font-medium shrink-0 px-2 py-1 rounded-lg hover:bg-blue-500/10 transition-all"
                        >
                          Copy
                        </button>
                      </div>

                      <button
                        onClick={handleClose}
                        className="w-full mt-1 bg-slate-700 hover:bg-slate-600 text-white font-medium py-2.5 rounded-xl transition-colors"
                      >
                        Done
                      </button>
                    </motion.div>
                  ) : (
                    /* Form state */
                    <motion.form
                      key="form"
                      onSubmit={handleSubmit}
                      className="flex flex-col gap-4"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                    >
                      {[
                        { label: 'Full Name', name: 'name', type: 'text', placeholder: 'e.g. Ali Hassan', required: true },
                        { label: 'Roll Number (Student ID)', name: 'rollNumber', type: 'text', placeholder: 'e.g. CS-2024-001  or  101', required: true },
                      ].map((field) => (
                        <div key={field.name}>
                          <label
                            htmlFor={`add-${field.name}`}
                            className="block text-sm font-medium text-slate-300 mb-1.5"
                          >
                            {field.label}
                          </label>
                          <input
                            id={`add-${field.name}`}
                            name={field.name}
                            type={field.type}
                            value={form[field.name]}
                            onChange={handleChange}
                            placeholder={field.placeholder}
                            required={field.required}
                            className="w-full bg-slate-800 border border-slate-600/50 text-white placeholder-slate-500 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500/30 transition-all"
                          />
                        </div>
                      ))}

                      {/* Field/Class dropdown */}
                      <div>
                        <label htmlFor="add-field" className="block text-sm font-medium text-slate-300 mb-1.5">
                          Class / Field
                        </label>
                        <input
                          id="add-field"
                          name="field"
                          type="text"
                          value={form.field}
                          onChange={handleChange}
                          placeholder="e.g. CS, IT, BBA, Matric-A"
                          className="w-full bg-slate-800 border border-slate-600/50 text-white placeholder-slate-500 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500/30 transition-all"
                        />
                        <p className="text-xs text-slate-500 mt-1">Optional — you will be able to filter by this field later</p>
                      </div>

                      {/* Email */}
                      {[{ label: 'Email Address (Optional)', name: 'email', type: 'email', placeholder: 'student@example.com', required: false },
                      ].map((field) => (
                        <div key={field.name}>
                          <label
                            htmlFor={`add-${field.name}`}
                            className="block text-sm font-medium text-slate-300 mb-1.5"
                          >
                            {field.label}
                          </label>
                          <input
                            id={`add-${field.name}`}
                            name={field.name}
                            type={field.type}
                            value={form[field.name]}
                            onChange={handleChange}
                            placeholder={field.placeholder}
                            required={field.required}
                            className="w-full bg-slate-800 border border-slate-600/50 text-white placeholder-slate-500 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500/30 transition-all"
                          />
                        </div>
                      ))}

                      {error && (
                        <motion.p
                          className="text-rose-400 text-sm bg-rose-500/10 border border-rose-500/20 rounded-xl px-3 py-2"
                          initial={{ opacity: 0, height: 0 }}
                          animate={{ opacity: 1, height: 'auto' }}
                        >
                          {error}
                        </motion.p>
                      )}

                      <div className="flex gap-3 mt-1">
                        <button
                          type="button"
                          onClick={handleClose}
                          className="flex-1 bg-slate-700/50 hover:bg-slate-700 text-slate-300 font-medium py-2.5 rounded-xl transition-colors"
                        >
                          Cancel
                        </button>
                        <button
                          type="submit"
                          disabled={loading}
                          className="flex-1 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 disabled:cursor-not-allowed text-white font-medium py-2.5 rounded-xl transition-colors flex items-center justify-center gap-2"
                        >
                          {loading ? (
                            <>
                              <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                              </svg>
                              Adding...
                            </>
                          ) : (
                            'Add Student'
                          )}
                        </button>
                      </div>
                    </motion.form>
                  )}
                </AnimatePresence>
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
};

export default AddStudentModal;
